notifications:
  email: false
addons:
  apt:
    packages:
    # These packages are required for testing PyQT5 applications on linux
    - x11-utils
    - libxkbcommon-x11-0
matrix:
 include:
 - os: osx
   language: generic
   env:
    # see https://www.python.org/downloads/mac-osx/ for valid versions
    - MAC_PYTHON_VERSION=3.6.8
    - MAC_PYTHON_OSX_VERSION=10.6
   sudo: required
 - os: linux
   language: python
   python: 3.6
   services: xvfb
install:
# install other dependencies
- source ./.travis/${TRAVIS_OS_NAME}_setup_python.sh $MAC_PYTHON_VERSION $MAC_PYTHON_OSX_VERSION
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
- travis_retry pip install -e .
# Linux tests did not complete
- travis_retry pip install threadpoolctl==2.0.0
- travis_retry pip install PyQt5==5.14.2 PyQt5-sip==12.7.2
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
- coverage run --source=dckit setup.py test
- coverage report -m
- flake8 dckit
- flake8 tests
# build step
- python setup.py sdist bdist_wheel
# https://github.com/pyinstaller/pyinstaller/issues/4626
- pip install pyinstaller==3.6
- bash ./.travis/${TRAVIS_OS_NAME}_build_app.sh DCKitApp $TRAVIS_TAG
after_success:
- codecov
deploy:
  - provider: pypi
    user: "ci_zmdd"
    password:
      secure: "QGidsFXX0mf5HaPQ/KCVwHwrCUQM8Nhcey4MTNvtj/dxpIuuZAhKZvqk5ps0tZ0OzCYp8ndZxqSGfN7Ek0OTqXn0iKtnBJBeWOvGXFkeF4VR3PVeHMUsyidUAgLnsGXNAMT40wopEh+PHeSRNicLC1s8fUNA72B918xuSH84gLixCCiZiBcruSkX9097xzKbLrB3x2VDAMsL6VS+laOqTWfzwvEjYs5jlgJ4U6lr3QsJNSLufMAFCVg+VI3v1zBajMVnBJf+BWbvrJEHIjI04TEva12kO6IMbf6IhWXqN2xoE57H1rtdQu0CPV6MynifDOMse9IOssu0JQpkShPeLc87cVVaYbSJgc4+LShYfN6FEa7AFqp/XZy0HOmDCLHSichCTe9FGqzwwxJdxloCuijBdFCiqgdvGsXWF9e2RQWTofgCUe2habWVfLeC+Ssw8N8ZzJ5PpFPLOa6gdfkrYLvrhqLvrH9bloKWVAFHEWiiXmFiFGuIjAXhYJylz1NGpRAZqLoaCh/Qe4QpxGioh1IsIRngrM03NoEkWTVFLkPYYwNGBpl7uusvnkXWpFt8D+cHTVGdLtcRvoz5yJJjZKIM5+uA48vefo9dGDQAm0T1J9+dIJR/qWAiVDm2Edb+gBEGNZlGRfTLNy8qZF8ldEtro1xVjvI6wAS2wzPTiyo="
    on:
      tags: true
    skip_cleanup: true
    skip_existing: true
  - provider: releases
    api_key:
      secure: "RLDO1n/gGukCStAJA2TxkC0nxFrJkqHsWhNrrXVHNKll9SS45X5EFfbvmdj8AJLd8wvlYyHHl7/C6DXucoTrVowCDVGrinxlEA2PAJR9vJMhk1FcS/pZO+9ZmC+EyEvxD6AjwGRBIy4ip1/qg9YMYD18F8qCUkauX/IXe339oD7mUAEnMS3JlkKQzU2na6imE0ivsIVXrDkhs+D0msoCt9OLtUHvNK9iHzbFv8wF4xAtxT5N4sZPQczsbfJXWYJ5olKZST41yYjWPE9pn8VxzhIDlozEYzvDmI6idFxuVHm+9M111fC2ZAJAduwzPylEqGGrHPyQhftspHeqAxQwuvm0uu2RlYdl1ioFnmwpCRmLXAJ5ZnBVSAb22hTKlze6CdfYJS5M48YtBPB2Oiw5Gr4Fafg+Za1K5IpdpnGBrLWYmC9mn+Qjy+Ps1Ss6g09uE2AFe/oX0Cwnt3DLLLlWOAUUFNOqoDyLZjHZfMd/trA09EuQvqKR4puoNzINcAW+4/i+rTD9k85sY5pT3DXJ3MBFkEGlylyCUycSEKEz4f78SVyV4jcBsixR04CXmyzvYQpDjqudhRkXrJAW1l7QTNn97gPY2KZnGmdp94s4NFFUI5TDHFZ5PwepUBLALUDt0qrRtNGg0ayoY9y523D4BA/wISQbRxYLN6YqRWF1+yo="
    file_glob: true
    file:
      - "dist_app/*.dmg"
      - "dist_app/*.pkg"
    skip_cleanup: true
    draft: true
    on:
      tags: true

